spring.datasource.url=jdbc:mysql://localhost:3306/billmitra?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
whatsapp.verify.token=billmitra123
twilio.account.sid=AC3b5be5c349235ed3c888bdc506a8cda4
twilio.auth.token=e0b242689e6797b90d9b1fb1a30c3472
twilio.whatsapp.number=whatsapp:+14155238886
groq.api.key=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