
spring.datasource.url=jdbc:mysql://mysql-161c0be3-shivamkashyap186-f292.e.aivencloud.com:15026/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_aTjKqkDGQnnWIdvU5xA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
whatsapp.verify.token=billmitra123
twilio.account.sid=AC3b5be5c349235ed3c888bdc506a8cda4
twilio.auth.token=e0b242689e6797b90d9b1fb1a30c3472
twilio.whatsapp.number=whatsapp:+14155238886
groq.api.key=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